### ISSUE TITLE
Create start template on Django

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#1]
### Tasks

- [x] Create start page
- [x] Create database and tests for this
- [x] Create super-users
- [x] Fix lint problems
- [x] Show data in admin panel
- [x] Create form on start page
- [ ] Find out how to take songs from _YouTube Music_, _YouTube_, _Spotify_ and ext., maybe there are some **API**
- [x] Fix old Django version in all files

> some tasks will add later

### Literature

- My wiki [tutorial](https://github.com/mezgoodle/django-tutorial/wiki)
- [Video](https://www.youtube.com/watch?v=w4nrT7emiVc) on YouTube
- [Video](https://www.youtube.com/watch?v=6K83dgjkQNw) on YouTube

### Branch

[django](https://github.com/mezidia/song-helper/tree/django)

### Folder

[server](https://github.com/mezidia/song-helper/tree/django/server)

**Comment by mezgoodle** [comment]
```bash
python manage.py createsuperuser
```
https://github.com/mezgoodle/django-tutorial/wiki/Models#work-with-admin-panel

**Comment by mezgoodle** [comment]
`Find out how to take songs from YouTube Music, YouTube, Spotify and ext., maybe there are some API`
This task delay on next issue

**Comment by mezgoodle** [comment]
> `Find out how to take songs from YouTube Music, YouTube, Spotify and ext., maybe there are some API`
> This task delay on next issue

Resolved in #26
