### ISSUE TITLE
Create start structure of Telegram bot

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#2]
### Tasks

- [x] Create start commands
- [x] Create tests
- [x] Find out how to send audio files in Telegram and how to take them from _Internet sites_
- [x] Create connection with server by requests

> some tasks will add later

### Literature

- My bots: [keepTelegram](https://github.com/mezgoodle/keepTelegram) and [VTL-Schedule-Bot](https://github.com/mezgoodle/VTL-Schedule-Bot)
- [Video](https://www.youtube.com/watch?v=M8fhrtvedHA) on YouTube (pyTelegramBotApi)
- [Video](https://www.youtube.com/watch?v=bXxa9IkAPew) on YouTube (aiogram)
- [Video](https://www.youtube.com/watch?v=QoJ_yvPttlc) on YouTube (pyTelegramBotApi)

### Branch

[bot](https://github.com/mezidia/song-helper/tree/bot)

### Folder

[bot](https://github.com/mezidia/song-helper/tree/bot/bot)
