### ISSUE TITLE
Understand how to work with AI on Python

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#3]
### Tasks

- [x] Understand how to start our work
- [x] Create some small script with data and results (@mezgoodle )
- [x] Add ML With SKlearn (@VsIG-official )

- [x] Create tests

> some tasks will add later

### Literature

- [Python libraries](https://github.com/vinta/awesome-python)
- [Course](https://lab.github.com/everydeveloper/advance-tensorflow) on GitHub
- [Book](https://t.me/techrocksarchive/1289)
- [Video](https://www.youtube.com/watch?v=WFYxpi3O950) on YouTube
- [Video](https://www.youtube.com/watch?v=iIOKHKwi2TE) on YouTube
- [Video](https://www.youtube.com/watch?v=kUDOcl9anxU) on YouTube
- [TensorFlow tutorial](https://www.youtube.com/watch?v=tPYj3fFJGjk)
- [Article about Neural Training](https://hackernoon.com/how-to-create-a-simple-neural-network-using-python-6o2d33yo)
- [Predicting the Music Mood of a Song with Deep Learning](https://towardsdatascience.com/predicting-the-music-mood-of-a-song-with-deep-learning-c3ac2b45229e)
- [Word Embeddings in Python with Spacy and Gensim](https://www.shanelynn.ie/word-embeddings-in-python-with-spacy-and-gensim/)
- [Use Sentiment Analysis With Python to Classify Movie Reviews](https://realpython.com/sentiment-analysis-python/#using-natural-language-processing-to-preprocess-and-clean-text-data)
- [«Люблю» и «ненавижу»: анализ эмоциональной окраски текста с помощью Python](https://proglib.io/p/lyublyu-i-nenavizhu-analiz-emocionalnoy-okraski-teksta-s-pomoshchyu-python-2020-11-13)
- [Emotion Detection from an Input Text Using Python](https://oindrilasen.com/2020/08/emotion-detection-from-an-input-text-using-python/)
- [Sentiment Analysis Python - 10 - Positive or Negative Sentiments | NLTK](https://www.youtube.com/watch?v=HtYweBOCp7A)
- [Training a model to recognize sentiment in text (NLP Zero to Hero - Part 3)](https://www.youtube.com/watch?v=Y_hzMnRXjhI&list=PLQY2H8rRoyvzDbLUZkbudP-MFQZwNmU4S&index=4)

### Branch

[song-helper](https://github.com/mezidia/song-helper/tree/song-helper)

### Folder

[song-helper](https://github.com/mezidia/song-helper/tree/song-helper/song-helper)

**Comment by mezgoodle** [comment]
@VsIG-official 
Write tasks for you connected with `word-embedding`

**Comment by VsIG-official** [comment]
Done

**Comment by mezgoodle** [comment]
@VsIG-official 
Can we close this issue?

**Comment by VsIG-official** [comment]
Yep
