### ISSUE TITLE
Improve Django

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#30]
### Tasks

- [x] Write form sending logic
- [x] Show result after form sending
- [x] Create page about adding song to database
- [x] Show result as song video on index page
- [x] Improve design

> some tasks will add later

### Literature

- From last [issue](https://github.com/mezidia/song-helper/issues/1)

### Branch

[django](https://github.com/mezidia/song-helper/tree/django)

### Folder

[server](https://github.com/mezidia/song-helper/tree/django/server)
