### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by VsIG-official** [mezidia/song-helper#32]
### Tasks

- [x] Create some basic functionality for Discord Bot
- [x] Make bot alive FOREVER
-------
- [x] Make Pause function
- [x] Make Resume function
-------
Possible tasks to do:
- [x] Make Queue function
- [x] Delete downloaded music, after some time or when track has ended
- [x] Add "async with ctx.typing():" to all functions
- [ ] Make Replay\Loop function
- [ ] Make Skip function
- [ ] Connect bot via [play] command
-------
Bugs:
- [ ] When Bot goes to the [play_next] function with one song in queue and You add new song, then this song won't play
- [ ] Fix strange error "TypeError: object NoneType can't be used in 'await' expression", while invoking [resume] or [pause] functions
-------
- [ ] Add music searching, like pancake bot

> some tasks will add later

### Literature

- [Mezgoodle's repo](https://github.com/mezgoodle/discordHots)
- [Video about Discord Bots](https://www.youtube.com/watch?v=SPTfmiYiuok&feature=emb_logo)
- [Video About Music Bots](https://www.youtube.com/watch?v=6gDmWekivmM&ab_channel=AnsontheDeveloper)
- [Nice video with searching audios on YouTube (only js)](https://www.youtube.com/watch?v=6gDmWekivmM&ab_channel=AnsontheDeveloper)
- [Discord.py](https://github.com/Rapptz/discord.py)
- [YouTube Playlist](https://youtube.com/playlist?list=PLW3GfRiBCHOhfVoiDZpSz8SM_HybXRPzZ)
- [Youtube](https://youtu.be/1liVAQdAEKA)
- [old version on YouTube](https://youtu.be/MbhXIddT2YY)
- [Article](https://medium.com/pythonland/build-a-discord-bot-in-python-that-plays-music-and-send-gifs-856385e605a1)

### Branch

[Discord-Bot](https://github.com/mezidia/song-helper/tree/Discord-Bot)

### Folder

[Discord-Bot](https://github.com/mezidia/song-helper/tree/Discord-Bot/Discord-Bot)

**Comment by mezgoodle** [comment]
Whoooray!

**Comment by VsIG-official** [comment]
![image](https://user-images.githubusercontent.com/50269023/113851987-b6aaa700-97a4-11eb-9951-48ea96cd3ca1.png)
