### ISSUE TITLE
Start develop the mobile app

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#35]
### Tasks

- [x] Create start app
- [x] Create unit tests
- [x] Make TODOs in programm
- [x] Improve design
- [x] Learn how to work with _.kv_ files
- [ ] Make CI for building programs for all platforms:
    - [ ] Windows
    - [ ] Linux
    - [ ] Android
    - [ ] IOS

> some tasks will add later

### Literature

- [Article from RealPython](https://realpython.com/mobile-app-kivy-python/)
- [Kivy documentation](https://kivy.org/doc/stable/)
- [KivyMD repository](https://github.com/kivymd/KivyMD) and [Article on Habr](https://habr.com/ru/post/422721/)
- Kivy tutorials playlists: in [English](https://www.youtube.com/watch?v=bMHK6NDVlCM&list=PLzMcBGfZo4-kSJVMyYeOQ8CXJ3z1k7gHn), in [Russian](https://www.youtube.com/watch?v=VIy3hktYKwE&list=PLvoBekrlHDgT2t0PH1J1VT_Bk2ziEAWMs)
- [Article](https://habr.com/ru/post/479236/) about compiling into Android platform

### Branch

[mobile-app](https://github.com/mezidia/song-helper/tree/mobile-app)

### Folder

[mobileApp](https://github.com/mezidia/song-helper/tree/mobile-app/mobileApp)

**Comment by mezgoodle** [comment]
@VsIG-official 
I have written some code, you can test it on your computer. I can write TODOs task. You can take another ones. I _updated_ **tasks** and **links**
