### ISSUE TITLE
Future tasks

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#45]
### Tasks

- [x] Fix libraries compability (taken @mezgoodle)
- [x] Host our datasets (taken @mezgoodle)
- [ ] Create Audio Visualiser for dJango (as code or gif) (taken @fhrr-sht and @VsIG-official)
- [x] Connect songhelper folder (taken @VsIG-official)
- [ ] Make Icon for Project (taken @fhrr-sht)
- [ ] Make docker image for Discord Bot (taken @VsIG-official)
- [x] Make docker image for Mobile App (taken @Dmytrenko-Roman)
- [ ] Deploy (non-taken)
- [x] Update workflows, such as exclude new packages (taken @mezgoodle)

> some tasks will add later

### Branch

[nothing](nothing)

### Folder

[nothing](nothing)

**Comment by mezgoodle** [comment]
@VsIG-official , add something I forgot

**Comment by mezgoodle** [comment]
@VsIG-official 
Please write which datasets you need for you script

**Comment by VsIG-official** [comment]
I'll delete some unused,but there are few datasets, which can be helpful in the future, so, maybe, We need to save them

**Comment by mezgoodle** [comment]
> I'll delete some unused,but there are few datasets, which can be helpful in the future, so, maybe, We need to save them

Say me which, because I am working with hosting proccess

**Comment by VsIG-official** [comment]
Right now We need only [OurData.csv]

**Comment by Dmytrenko-Roman** [comment]
➕ I will make Docker Image for Mobile App ➕

**Comment by VsIG-official** [comment]
> ➕ I will make Docker Image for Mobile App ➕

That's cool, but We don't have Mobile App yet
